export const TIPOS_TRAMITE = {
  PERMISO: 'PERMISO',
  LICENCIA: 'LICENCIA',
};

export const ESTADOS_TRAMITE = [
  { value: 'BORRADOR', label: 'Borrador', color: 'secondary' },
  { value: 'REVISION', label: 'En Revisión', color: 'info' },
  { value: 'INSPECCION', label: 'En Inspección', color: 'warning' },
  { value: 'DOCUMENTO_GENERADO', label: 'Documento Generado', color: 'primary' },
  { value: 'APROBADO', label: 'Aprobado', color: 'success' },
  { value: 'RECHAZADO', label: 'Rechazado', color: 'danger' },
];

export const SUBTIPOS_PERMISO = [
  'Forestal',
  'Hídrico',
  'Manejo de Residuos',
  'Emisiones Atmosféricas',
  'Construcción',
  'Uso de Suelo',
];

export const SUBTIPOS_LICENCIA = [
  'Operación',
  'Construcción',
  'Modificación',
  'Renovación',
  'Ampliación',
];

export const FORM_INICIAL_TRAMITE = {
  id: '',
  tipo: TIPOS_TRAMITE.PERMISO,
  subtipo: '',
  solicitante: '',
  cedulaRif: '',
  direccion: '',
  municipio: '',
  estado_geografico: '',
  telefono: '',
  email: '',
  descripcion: '',
  documentos: [],
  estado: 'REVISION',
  inspectorId: null,
  inspectorNombre: '',
  fechaSolicitud: '',
  fechaRevision: null,
  fechaInspeccion: null,
  fechaDocumento: null,
  fechaAprobacion: null,
  observaciones: '',
  historial: [],
};

export const DATOS_INICIALES_TRAMITES = [
  {
    id: 'PER-2026-001',
    tipo: TIPOS_TRAMITE.PERMISO,
    subtipo: 'Forestal',
    solicitante: 'Empresa Maderera C.A.',
    cedulaRif: 'J-12345678-9',
    direccion: 'Av. Principal, Sector El Bosque',
    municipio: 'Libertador',
    estado_geografico: 'Distrito Capital',
    telefono: '+58 412-555-1111',
    email: 'contacto@maderera.com',
    descripcion: 'Solicitud de permiso de aprovechamiento forestal para 50 hectáreas',
    documentos: ['solicitud.pdf', 'plano_ubicacion.pdf'],
    estado: 'REVISION',
    inspectorId: null,
    inspectorNombre: '',
    fechaSolicitud: '2026-05-01',
    fechaRevision: null,
    fechaInspeccion: null,
    fechaDocumento: null,
    fechaAprobacion: null,
    observaciones: '',
    historial: [
      { estado: 'REVISION', fecha: '2026-05-01T10:30:00', usuario: 'Sistema', nota: 'Solicitud recibida' },
    ],
  },
  {
    id: 'LIC-2026-001',
    tipo: TIPOS_TRAMITE.LICENCIA,
    subtipo: 'Operación',
    solicitante: 'Industrias Ambientales S.A.',
    cedulaRif: 'J-98765432-1',
    direccion: 'Zona Industrial, Galpón 15',
    municipio: 'Sucre',
    estado_geografico: 'Miranda',
    telefono: '+58 416-555-2222',
    email: 'info@industriasamb.com',
    descripcion: 'Licencia ambiental para operación de planta de reciclaje',
    documentos: ['solicitud.pdf', 'estudio_impacto.pdf'],
    estado: 'INSPECCION',
    inspectorId: 'NORTE-INSPECTOR-001',
    inspectorNombre: 'María González',
    fechaSolicitud: '2026-04-15',
    fechaRevision: '2026-04-20',
    fechaInspeccion: null,
    fechaDocumento: null,
    fechaAprobacion: null,
    observaciones: '',
    historial: [
      { estado: 'REVISION', fecha: '2026-04-15T09:00:00', usuario: 'Sistema', nota: 'Solicitud recibida' },
      { estado: 'REVISION', fecha: '2026-04-20T14:00:00', usuario: 'Secretaría', nota: 'Documentación completa, aprobada para inspección' },
      { estado: 'INSPECCION', fecha: '2026-04-22T08:00:00', usuario: 'Secretaría', nota: 'Inspector María González asignada' },
    ],
  },
  {
    id: 'PER-2026-002',
    tipo: TIPOS_TRAMITE.PERMISO,
    subtipo: 'Hídrico',
    solicitante: 'Agropecuaria El Valle',
    cedulaRif: 'V-15678901-3',
    direccion: 'Finca La Esperanza, Km 12',
    municipio: 'Los Salias',
    estado_geografico: 'Miranda',
    telefono: '+58 414-555-3333',
    email: 'elvalle@agro.com',
    descripcion: 'Permiso de captación de agua de río para riego agrícola',
    documentos: ['solicitud.pdf'],
    estado: 'APROBADO',
    inspectorId: 'NORTE-INSPECTOR-001',
    inspectorNombre: 'María González',
    fechaSolicitud: '2026-03-10',
    fechaRevision: '2026-03-15',
    fechaInspeccion: '2026-03-20',
    fechaDocumento: '2026-03-25',
    fechaAprobacion: '2026-03-28',
    observaciones: 'Providencia firmada por el Director',
    historial: [
      { estado: 'REVISION', fecha: '2026-03-10T10:00:00', usuario: 'Sistema', nota: 'Solicitud recibida' },
      { estado: 'INSPECCION', fecha: '2026-03-18T09:00:00', usuario: 'Secretaría', nota: 'Inspector asignado' },
      { estado: 'DOCUMENTO_GENERADO', fecha: '2026-03-25T11:00:00', usuario: 'Secretaría', nota: 'Providencia generada' },
      { estado: 'APROBADO', fecha: '2026-03-28T16:00:00', usuario: 'Secretaría', nota: 'Documento firmado y aprobado' },
    ],
  },
  {
    id: 'LIC-2026-002',
    tipo: TIPOS_TRAMITE.LICENCIA,
    subtipo: 'Renovación',
    solicitante: 'Constructora Bolívar C.A.',
    cedulaRif: 'J-45678901-2',
    direccion: 'Torre Empresarial, Piso 8',
    municipio: 'Baruta',
    estado_geografico: 'Miranda',
    telefono: '+58 424-555-4444',
    email: 'legal@constructorabolivar.com',
    descripcion: 'Renovación de licencia ambiental para proyecto urbanístico',
    documentos: ['solicitud.pdf', 'licencia_anterior.pdf', 'informe_cumplimiento.pdf'],
    estado: 'RECHAZADO',
    inspectorId: null,
    inspectorNombre: '',
    fechaSolicitud: '2026-04-01',
    fechaRevision: '2026-04-05',
    fechaInspeccion: null,
    fechaDocumento: null,
    fechaAprobacion: null,
    observaciones: 'Documentación incompleta: falta informe de impacto ambiental actualizado',
    historial: [
      { estado: 'REVISION', fecha: '2026-04-01T08:30:00', usuario: 'Sistema', nota: 'Solicitud recibida' },
      { estado: 'RECHAZADO', fecha: '2026-04-05T15:00:00', usuario: 'Secretaría', nota: 'Documentación incompleta' },
    ],
  },
];
