export const ROLES_EQUIPO = {
  OPERATIVO: 'OPERATIVO',
  TECNICO_INSPECTOR: 'TECNICO_INSPECTOR',
};

export const ZONAS_OPERACION = [
  { value: 'Zona Norte', label: 'Zona Norte' },
  { value: 'Zona Sur', label: 'Zona Sur' },
  { value: 'Zona Este', label: 'Zona Este' },
  { value: 'Zona Oeste', label: 'Zona Oeste' },
  { value: 'Zona Central', label: 'Zona Central' },
];

export const ESTADOS_CUADRILLA = [
  { value: 'activa', label: 'Activa', color: 'success' },
  { value: 'inactiva', label: 'Inactiva', color: 'secondary' },
  { value: 'ocupada', label: 'Ocupada', color: 'warning' },
  { value: 'mantenimiento', label: 'En Mantenimiento', color: 'info' },
];

export const ESPECIALIDADES_DISPONIBLES = [
  'deforestacion',
  'contaminacion_agua',
  'fauna_silvestre',
  'residuos_solidos',
  'incendios_forestales',
  'mineria_ilegal',
  'vertidos_quimicos',
  'inspeccion_permisos',
  'evaluacion_licencias',
];

export const MODULOS_ORIGEN = {
  denuncias: { label: 'Denuncia', color: 'danger', icon: 'cilWarning' },
  permisos: { label: 'Permiso', color: 'primary', icon: 'cilTask' },
  licencias: { label: 'Licencia', color: 'info', icon: 'cilDescription' },
};

export const FORM_INICIAL = {
  id: '',
  nombre: '',
  zona: '',
  responsables: '',
  telefono: '',
  capacidad: 3,
  especialidad: [],
  coordenadas: { lat: '', lng: '' },
  estado: 'activa',
  empleadosAsignados: [],
  integrantes: [],
  rol: ROLES_EQUIPO.OPERATIVO,
};

export const DATOS_INICIALES_CUADRILLAS = [
  {
    id: 'NORTE-OBREROS-001',
    nombre: 'NORTE-OBREROS-001',
    zona: 'Zona Norte',
    supervisor: 'Carlos Rodríguez',
    supervisorId: 1,
    telefono: '+58 412-555-0101',
    responsables: ['Carlos Rodríguez', 'María González', 'Ana Martínez'],
    integrantes: [2, 3],
    especialidad: ['deforestacion', 'fauna_silvestre'],
    coordenadas: { lat: '10.5412', lng: '-66.8765' },
    estado: 'activa',
    disponible: true,
    tareasActuales: [],
    rol: ROLES_EQUIPO.OPERATIVO,
  },
  {
    id: 'SUR-OBREROS-001',
    nombre: 'SUR-OBREROS-001',
    zona: 'Zona Sur',
    supervisor: 'Ana Martínez',
    supervisorId: 2,
    telefono: '+58 416-555-0202',
    responsables: ['Ana Martínez', 'Luis Pérez'],
    integrantes: [4],
    especialidad: ['contaminacion_agua', 'residuos_solidos'],
    coordenadas: { lat: '10.1203', lng: '-67.0145' },
    estado: 'activa',
    disponible: true,
    tareasActuales: [],
    rol: ROLES_EQUIPO.OPERATIVO,
  },
  {
    id: 'CENTRAL-OBREROS-001',
    nombre: 'CENTRAL-OBREROS-001',
    zona: 'Zona Central',
    supervisor: 'Luis Pérez',
    supervisorId: 4,
    telefono: '+58 424-555-0303',
    responsables: ['Luis Pérez', 'Sofía Torres', 'Pedro Sánchez'],
    integrantes: [5, 6],
    especialidad: ['inspeccion_permisos', 'evaluacion_licencias'],
    coordenadas: { lat: '10.3456', lng: '-66.9012' },
    estado: 'ocupada',
    disponible: false,
    tareasActuales: [{ moduloOrigen: 'permisos', tareaId: 'PER-045', descripcion: 'Inspección Permiso Forestal #45' }],
    rol: ROLES_EQUIPO.OPERATIVO,
  },
  {
    id: 'ESTE-OBREROS-001',
    nombre: 'ESTE-OBREROS-001',
    zona: 'Zona Este',
    supervisor: 'Sofía Torres',
    supervisorId: 5,
    telefono: '+58 414-555-0404',
    responsables: ['Sofía Torres'],
    integrantes: [],
    especialidad: ['mineria_ilegal', 'vertidos_quimicos'],
    coordenadas: { lat: '10.4567', lng: '-66.1234' },
    estado: 'inactiva',
    disponible: false,
    tareasActuales: [],
    rol: ROLES_EQUIPO.OPERATIVO,
  },
  {
    id: 'NORTE-INSPECTOR-001',
    nombre: 'NORTE-INSPECTOR-001',
    zona: 'Zona Norte',
    supervisor: 'María González',
    supervisorId: 3,
    telefono: '+58 412-555-0505',
    responsables: ['María González'],
    integrantes: [3],
    especialidad: ['inspeccion_permisos', 'evaluacion_licencias'],
    coordenadas: { lat: '10.5500', lng: '-66.8800' },
    estado: 'activa',
    disponible: true,
    tareasActuales: [],
    rol: ROLES_EQUIPO.TECNICO_INSPECTOR,
  },
];
